require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SongStatsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SongStat. As you add validations to SongStat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SongStatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all song_stats as @song_stats" do
      song_stat = SongStat.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:song_stats)).to eq([song_stat])
    end
  end

  describe "GET #show" do
    it "assigns the requested song_stat as @song_stat" do
      song_stat = SongStat.create! valid_attributes
      get :show, {:id => song_stat.to_param}, valid_session
      expect(assigns(:song_stat)).to eq(song_stat)
    end
  end

  describe "GET #new" do
    it "assigns a new song_stat as @song_stat" do
      get :new, {}, valid_session
      expect(assigns(:song_stat)).to be_a_new(SongStat)
    end
  end

  describe "GET #edit" do
    it "assigns the requested song_stat as @song_stat" do
      song_stat = SongStat.create! valid_attributes
      get :edit, {:id => song_stat.to_param}, valid_session
      expect(assigns(:song_stat)).to eq(song_stat)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SongStat" do
        expect {
          post :create, {:song_stat => valid_attributes}, valid_session
        }.to change(SongStat, :count).by(1)
      end

      it "assigns a newly created song_stat as @song_stat" do
        post :create, {:song_stat => valid_attributes}, valid_session
        expect(assigns(:song_stat)).to be_a(SongStat)
        expect(assigns(:song_stat)).to be_persisted
      end

      it "redirects to the created song_stat" do
        post :create, {:song_stat => valid_attributes}, valid_session
        expect(response).to redirect_to(SongStat.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved song_stat as @song_stat" do
        post :create, {:song_stat => invalid_attributes}, valid_session
        expect(assigns(:song_stat)).to be_a_new(SongStat)
      end

      it "re-renders the 'new' template" do
        post :create, {:song_stat => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested song_stat" do
        song_stat = SongStat.create! valid_attributes
        put :update, {:id => song_stat.to_param, :song_stat => new_attributes}, valid_session
        song_stat.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested song_stat as @song_stat" do
        song_stat = SongStat.create! valid_attributes
        put :update, {:id => song_stat.to_param, :song_stat => valid_attributes}, valid_session
        expect(assigns(:song_stat)).to eq(song_stat)
      end

      it "redirects to the song_stat" do
        song_stat = SongStat.create! valid_attributes
        put :update, {:id => song_stat.to_param, :song_stat => valid_attributes}, valid_session
        expect(response).to redirect_to(song_stat)
      end
    end

    context "with invalid params" do
      it "assigns the song_stat as @song_stat" do
        song_stat = SongStat.create! valid_attributes
        put :update, {:id => song_stat.to_param, :song_stat => invalid_attributes}, valid_session
        expect(assigns(:song_stat)).to eq(song_stat)
      end

      it "re-renders the 'edit' template" do
        song_stat = SongStat.create! valid_attributes
        put :update, {:id => song_stat.to_param, :song_stat => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested song_stat" do
      song_stat = SongStat.create! valid_attributes
      expect {
        delete :destroy, {:id => song_stat.to_param}, valid_session
      }.to change(SongStat, :count).by(-1)
    end

    it "redirects to the song_stats list" do
      song_stat = SongStat.create! valid_attributes
      delete :destroy, {:id => song_stat.to_param}, valid_session
      expect(response).to redirect_to(song_stats_url)
    end
  end

end
